version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: nestjs-sst-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
   

  nestjs-kysely:
    image: nestjs-kysely
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: nestjs-kysely
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env

      

volumes:
  postgres-data: