version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
   
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nestjs-drizzle-boilerplate:
    image: nestjs-drizzle-boilerplate
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: nestjs-drizzle-boilerplate-app
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@postgres:5432/mydb
      - PORT=${PORT}
      - NODE_ENV=production

    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres

      

volumes:
  postgres-data: