version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: nestjs-sst-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  nestjs-kysely:
    image: nestjs-kysely
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-kysely
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
    - ./src:/app/src
    env_file:
      - .env

    environment:
      - NODE_ENV=development
      - PORT=3000
      

volumes:
  postgres-data: